export interface Country {
  name: string;
  code: string;
  iso: string;
}

export const countries: Country[] = [
  { name: "Andorra", code: "+376", iso: "ad" },
  { name: "United Arab Emirates", code: "+971", iso: "ae" },
  { name: "Afghanistan", code: "+93", iso: "af" },
  { name: "Antigua and Barbuda", code: "+1-268", iso: "ag" },
  { name: "Anguilla", code: "+1-264", iso: "ai" },
  { name: "Albania", code: "+355", iso: "al" },
  { name: "Armenia", code: "+374", iso: "am" },
  { name: "Angola", code: "+244", iso: "ao" },
  { name: "Argentina", code: "+54", iso: "ar" },
  { name: "American Samoa", code: "+1-684", iso: "as" },
  { name: "Austria", code: "+43", iso: "at" },
  { name: "Australia", code: "+61", iso: "au" },
  { name: "Aruba", code: "+297", iso: "aw" },
  { name: "Åland Islands", code: "+358", iso: "ax" },
  { name: "Azerbaijan", code: "+994", iso: "az" },
  { name: "Bosnia and Herzegovina", code: "+387", iso: "ba" },
  { name: "Barbados", code: "+1-246", iso: "bb" },
  { name: "Bangladesh", code: "+880", iso: "bd" },
  { name: "Belgium", code: "+32", iso: "be" },
  { name: "Burkina Faso", code: "+226", iso: "bf" },
  { name: "Bulgaria", code: "+359", iso: "bg" },
  { name: "Bahrain", code: "+973", iso: "bh" },
  { name: "Burundi", code: "+257", iso: "bi" },
  { name: "Benin", code: "+229", iso: "bj" },
  { name: "Saint Barthélemy", code: "+590", iso: "bl" },
  { name: "Bermuda", code: "+1-441", iso: "bm" },
  { name: "Brunei", code: "+673", iso: "bn" },
  { name: "Bolivia", code: "+591", iso: "bo" },
  { name: "Bonaire, Sint Eustatius and Saba", code: "+599", iso: "bq" },
  { name: "Brazil", code: "+55", iso: "br" },
  { name: "Bahamas", code: "+1-242", iso: "bs" },
  { name: "Bhutan", code: "+975", iso: "bt" },
  { name: "Botswana", code: "+267", iso: "bw" },
  { name: "Belarus", code: "+375", iso: "by" },
  { name: "Belize", code: "+501", iso: "bz" },
  { name: "Canada", code: "+1", iso: "ca" },
  { name: "Cocos (Keeling) Islands", code: "+61", iso: "cc" },
  { name: "Democratic Republic of the Congo", code: "+243", iso: "cd" },
  { name: "Central African Republic", code: "+236", iso: "cf" },
  { name: "Republic of the Congo", code: "+242", iso: "cg" },
  { name: "Switzerland", code: "+41", iso: "ch" },
  { name: "Côte d'Ivoire", code: "+225", iso: "ci" },
  { name: "Cook Islands", code: "+682", iso: "ck" },
  { name: "Chile", code: "+56", iso: "cl" },
  { name: "Cameroon", code: "+237", iso: "cm" },
  { name: "China", code: "+86", iso: "cn" },
  { name: "Colombia", code: "+57", iso: "co" },
  { name: "Costa Rica", code: "+506", iso: "cr" },
  { name: "Cuba", code: "+53", iso: "cu" },
  { name: "Cape Verde", code: "+238", iso: "cv" },
  { name: "Curaçao", code: "+599", iso: "cw" },
  { name: "Christmas Island", code: "+61", iso: "cx" },
  { name: "Cyprus", code: "+357", iso: "cy" },
  { name: "Czech Republic", code: "+420", iso: "cz" },
  { name: "Germany", code: "+49", iso: "de" },
  { name: "Djibouti", code: "+253", iso: "dj" },
  { name: "Denmark", code: "+45", iso: "dk" },
  { name: "Dominica", code: "+1-767", iso: "dm" },
  { name: "Dominican Republic", code: "+1-809", iso: "do" },
  { name: "Algeria", code: "+213", iso: "dz" },
  { name: "Ecuador", code: "+593", iso: "ec" },
  { name: "Estonia", code: "+372", iso: "ee" },
  { name: "Egypt", code: "+20", iso: "eg" },
  { name: "Eritrea", code: "+291", iso: "er" },
  { name: "Spain", code: "+34", iso: "es" },
  { name: "Ethiopia", code: "+251", iso: "et" },
  { name: "Finland", code: "+358", iso: "fi" },
  { name: "Fiji", code: "+679", iso: "fj" },
  { name: "Falkland Islands", code: "+500", iso: "fk" },
  { name: "Micronesia", code: "+691", iso: "fm" },
  { name: "Faroe Islands", code: "+298", iso: "fo" },
  { name: "France", code: "+33", iso: "fr" },
  { name: "Gabon", code: "+241", iso: "ga" },
  { name: "United Kingdom", code: "+44", iso: "gb" },
  { name: "Grenada", code: "+1-473", iso: "gd" },
  { name: "Georgia", code: "+995", iso: "ge" },
  { name: "French Guiana", code: "+594", iso: "gf" },
  { name: "Guernsey", code: "+44-1481", iso: "gg" },
  { name: "Ghana", code: "+233", iso: "gh" },
  { name: "Gibraltar", code: "+350", iso: "gi" },
  { name: "Greenland", code: "+299", iso: "gl" },
  { name: "Gambia", code: "+220", iso: "gm" },
  { name: "Guinea", code: "+224", iso: "gn" },
  { name: "Guadeloupe", code: "+590", iso: "gp" },
  { name: "Equatorial Guinea", code: "+240", iso: "gq" },
  { name: "Greece", code: "+30", iso: "gr" },
  { name: "Guatemala", code: "+502", iso: "gt" },
  { name: "Guam", code: "+1-671", iso: "gu" },
  { name: "Guinea-Bissau", code: "+245", iso: "gw" },
  { name: "Guyana", code: "+592", iso: "gy" },
  { name: "Hong Kong", code: "+852", iso: "hk" },
  { name: "Honduras", code: "+504", iso: "hn" },
  { name: "Croatia", code: "+385", iso: "hr" },
  { name: "Haiti", code: "+509", iso: "ht" },
  { name: "Hungary", code: "+36", iso: "hu" },
  { name: "Indonesia", code: "+62", iso: "id" },
  { name: "Ireland", code: "+353", iso: "ie" },
  { name: "Israel", code: "+972", iso: "il" },
  { name: "Isle of Man", code: "+44-1624", iso: "im" },
  { name: "India", code: "+91", iso: "in" },
  { name: "Iraq", code: "+964", iso: "iq" },
  { name: "Iran", code: "+98", iso: "ir" },
  { name: "Iceland", code: "+354", iso: "is" },
  { name: "Italy", code: "+39", iso: "it" },
  { name: "Jersey", code: "+44-1534", iso: "je" },
  { name: "Jamaica", code: "+1-876", iso: "jm" },
  { name: "Jordan", code: "+962", iso: "jo" },
  { name: "Japan", code: "+81", iso: "jp" },
  { name: "Kenya", code: "+254", iso: "ke" },
  { name: "Kyrgyzstan", code: "+996", iso: "kg" },
  { name: "Cambodia", code: "+855", iso: "kh" },
  { name: "Kiribati", code: "+686", iso: "ki" },
  { name: "Comoros", code: "+269", iso: "km" },
  { name: "Saint Kitts and Nevis", code: "+1-869", iso: "kn" },
  { name: "North Korea", code: "+850", iso: "kp" },
  { name: "South Korea", code: "+82", iso: "kr" },
  { name: "Kuwait", code: "+965", iso: "kw" },
  { name: "Cayman Islands", code: "+1-345", iso: "ky" },
  { name: "Kazakhstan", code: "+7", iso: "kz" },
  { name: "Laos", code: "+856", iso: "la" },
  { name: "Lebanon", code: "+961", iso: "lb" },
  { name: "Saint Lucia", code: "+1-758", iso: "lc" },
  { name: "Liechtenstein", code: "+423", iso: "li" },
  { name: "Sri Lanka", code: "+94", iso: "lk" },
  { name: "Liberia", code: "+231", iso: "lr" },
  { name: "Lesotho", code: "+266", iso: "ls" },
  { name: "Lithuania", code: "+370", iso: "lt" },
  { name: "Luxembourg", code: "+352", iso: "lu" },
  { name: "Latvia", code: "+371", iso: "lv" },
  { name: "Libya", code: "+218", iso: "ly" },
  { name: "Morocco", code: "+212", iso: "ma" },
  { name: "Monaco", code: "+377", iso: "mc" },
  { name: "Moldova", code: "+373", iso: "md" },
  { name: "Montenegro", code: "+382", iso: "me" },
  { name: "Saint Martin", code: "+590", iso: "mf" },
  { name: "Madagascar", code: "+261", iso: "mg" },
  { name: "Marshall Islands", code: "+692", iso: "mh" },
  { name: "Macedonia", code: "+389", iso: "mk" },
  { name: "Mali", code: "+223", iso: "ml" },
  { name: "Myanmar", code: "+95", iso: "mm" },
  { name: "Mongolia", code: "+976", iso: "mn" },
  { name: "Macao", code: "+853", iso: "mo" },
  { name: "Martinique", code: "+596", iso: "mq" },
  { name: "Mauritania", code: "+222", iso: "mr" },
  { name: "Montserrat", code: "+1-664", iso: "ms" },
  { name: "Malta", code: "+356", iso: "mt" },
  { name: "Mauritius", code: "+230", iso: "mu" },
  { name: "Maldives", code: "+960", iso: "mv" },
  { name: "Malawi", code: "+265", iso: "mw" },
  { name: "Mexico", code: "+52", iso: "mx" },
  { name: "Malaysia", code: "+60", iso: "my" },
  { name: "Mozambique", code: "+258", iso: "mz" },
  { name: "Namibia", code: "+264", iso: "na" },
  { name: "New Caledonia", code: "+687", iso: "nc" },
  { name: "Niger", code: "+227", iso: "ne" },
  { name: "Nigeria", code: "+234", iso: "ng" },
  { name: "Nicaragua", code: "+505", iso: "ni" },
  { name: "Netherlands", code: "+31", iso: "nl" },
  { name: "Norway", code: "+47", iso: "no" },
  { name: "Nepal", code: "+977", iso: "np" },
  { name: "Nauru", code: "+674", iso: "nr" },
  { name: "Niue", code: "+683", iso: "nu" },
  { name: "New Zealand", code: "+64", iso: "nz" },
  { name: "Oman", code: "+968", iso: "om" },
  { name: "Panama", code: "+507", iso: "pa" },
  { name: "Peru", code: "+51", iso: "pe" },
  { name: "French Polynesia", code: "+689", iso: "pf" },
  { name: "Papua New Guinea", code: "+675", iso: "pg" },
  { name: "Philippines", code: "+63", iso: "ph" },
  { name: "Pakistan", code: "+92", iso: "pk" },
  { name: "Poland", code: "+48", iso: "pl" },
  { name: "Saint Pierre and Miquelon", code: "+508", iso: "pm" },
  { name: "Puerto Rico", code: "+1-787", iso: "pr" },
  { name: "Palestine", code: "+970", iso: "ps" },
  { name: "Portugal", code: "+351", iso: "pt" },
  { name: "Palau", code: "+680", iso: "pw" },
  { name: "Paraguay", code: "+595", iso: "py" },
  { name: "Qatar", code: "+974", iso: "qa" },
  { name: "Réunion", code: "+262", iso: "re" },
  { name: "Romania", code: "+40", iso: "ro" },
  { name: "Serbia", code: "+381", iso: "rs" },
  { name: "Russia", code: "+7", iso: "ru" },
  { name: "Rwanda", code: "+250", iso: "rw" },
  { name: "Saudi Arabia", code: "+966", iso: "sa" },
  { name: "Solomon Islands", code: "+677", iso: "sb" },
  { name: "Seychelles", code: "+248", iso: "sc" },
  { name: "Sudan", code: "+249", iso: "sd" },
  { name: "Sweden", code: "+46", iso: "se" },
  { name: "Singapore", code: "+65", iso: "sg" },
  { name: "Saint Helena", code: "+290", iso: "sh" },
  { name: "Slovenia", code: "+386", iso: "si" },
  { name: "Slovakia", code: "+421", iso: "sk" },
  { name: "Sierra Leone", code: "+232", iso: "sl" },
  { name: "San Marino", code: "+378", iso: "sm" },
  { name: "Senegal", code: "+221", iso: "sn" },
  { name: "Somalia", code: "+252", iso: "so" },
  { name: "Suriname", code: "+597", iso: "sr" },
  { name: "South Sudan", code: "+211", iso: "ss" },
  { name: "São Tomé and Príncipe", code: "+239", iso: "st" },
  { name: "El Salvador", code: "+503", iso: "sv" },
  { name: "Sint Maarten", code: "+1-721", iso: "sx" },
  { name: "Syria", code: "+963", iso: "sy" },
  { name: "Swaziland", code: "+268", iso: "sz" },
  { name: "Turks and Caicos Islands", code: "+1-649", iso: "tc" },
  { name: "Chad", code: "+235", iso: "td" },
  { name: "Togo", code: "+228", iso: "tg" },
  { name: "Thailand", code: "+66", iso: "th" },
  { name: "Tajikistan", code: "+992", iso: "tj" },
  { name: "Tokelau", code: "+690", iso: "tk" },
  { name: "Timor-Leste", code: "+670", iso: "tl" },
  { name: "Turkmenistan", code: "+993", iso: "tm" },
  { name: "Tunisia", code: "+216", iso: "tn" },
  { name: "Tonga", code: "+676", iso: "to" },
  { name: "Turkey", code: "+90", iso: "tr" },
  { name: "Trinidad and Tobago", code: "+1-868", iso: "tt" },
  { name: "Tuvalu", code: "+688", iso: "tv" },
  { name: "Taiwan", code: "+886", iso: "tw" },
  { name: "Tanzania", code: "+255", iso: "tz" },
  { name: "Ukraine", code: "+380", iso: "ua" },
  { name: "Uganda", code: "+256", iso: "ug" },
  { name: "United States", code: "+1", iso: "us" },
  { name: "Uruguay", code: "+598", iso: "uy" },
  { name: "Uzbekistan", code: "+998", iso: "uz" },
  { name: "Vatican City", code: "+39-06", iso: "va" },
  { name: "Saint Vincent and the Grenadines", code: "+1-784", iso: "vc" },
  { name: "Venezuela", code: "+58", iso: "ve" },
  { name: "British Virgin Islands", code: "+1-284", iso: "vg" },
  { name: "U.S. Virgin Islands", code: "+1-340", iso: "vi" },
  { name: "Vietnam", code: "+84", iso: "vn" },
  { name: "Vanuatu", code: "+678", iso: "vu" },
  { name: "Wallis and Futuna", code: "+681", iso: "wf" },
  { name: "Samoa", code: "+685", iso: "ws" },
  { name: "Yemen", code: "+967", iso: "ye" },
  { name: "Mayotte", code: "+262", iso: "yt" },
  { name: "South Africa", code: "+27", iso: "za" },
  { name: "Zambia", code: "+260", iso: "zm" },
  { name: "Zimbabwe", code: "+263", iso: "zw" }
];
